### ISSUE TITLE
Show result number at the top

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/bitcoinsearch-frontend#14]
<img width="1011" alt="Screen Shot 2023-01-11 at 1 57 17 PM" src="https://user-images.githubusercontent.com/755825/211896522-61af6398-8095-4a31-9839-42631f77e070.png">

Remove the "1-20" on left and default pull-down for the number of results listed on right and default it to the maximum (why not?). Replace with the total number of results (will have to check if that raw number is delivered from the API).

**Comment by Emmanuel-Develops** [comment]
@adamjonas, defaulting to the max will call all the results (14301) which will task the user's network and server. Or do you mean infinite scroll, at the end of the 20 results there's a call for the next 20 results?

**Comment by adamjonas** [comment]
Infinite scroll sounds good but we can start with 60 or 100 or whatever is easiest to start.

**Comment by adamjonas** [comment]
Let's display the number even if it maxes out at 10,000.

**Comment by adamjonas** [comment]
Closed via #15
