### ISSUE TITLE
Add date to results

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/bitcoinsearch-frontend#18]
If available, add a date to the result next to the author.

<img width="573" alt="Screen Shot 2023-01-16 at 8 08 39 PM" src="https://user-images.githubusercontent.com/755825/212788622-619f2da6-3b10-433b-a6ac-3ec6e257cd19.png">

**Comment by Emmanuel-Develops** [comment]
<img width="819" alt="Screenshot 2023-01-21 at 11 19 04 PM" src="https://user-images.githubusercontent.com/62019510/213889187-c795ed16-fe70-4796-8931-21aa4892a07c.png">

Date UI example. Made it an outline instead of a background to differentiate from tags

**Comment by adamjonas** [comment]
Looks good. Let's get it out and solicit feedback.
