### ISSUE TITLE
Add tags to results

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/bitcoinsearch-frontend#20]
Add tags to the pills at the bottom of each result.

Not sure on the colors here. Maybe it makes sense to differentiate.

A click on a pill should highlight that facet both in the sidebar and in the results. Clicking it again should remove the filter.

<img width="573" alt="Screen Shot 2023-01-16 at 8 08 39 PM" src="https://user-images.githubusercontent.com/755825/212790765-c9e6cc7a-02c2-4292-bac6-b5188ba16724.png">

**Comment by Emmanuel-Develops** [comment]
We are currently displaying authors as tags.

Does this implementation display all facet categories (i.e domain, authors, tags) as visual tags?
Maybe color coding depending on facet category?

**Comment by adamjonas** [comment]
We aren't displaying the authors as tags, it is just the first facet we listed. I don't know if it makes sense to display the domain in a pill given yo can see the url. I'd stick to tags for now.

Yes, it probably makes sense to differentiate.
