### ISSUE TITLE
User submitted content additions

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/bitcoinsearch-frontend#23]
As a searcher, if I don't find a source that I think should be indexed, I should be able to submit the URL for review to be added.

Not sure what the copy and interface are here, but a simple form submitted to a google sheet or something like that would be enough to get started.

**Comment by adamjonas** [comment]
Only the URL is necessary. If we get spam, we'll have to deal with it but just URL is fine for now.

Let's go with option 2 on sending to a form.

**Comment by Emmanuel-Develops** [comment]
For the contribution, I think it will be a nice addition not to have it only when no results are found. But also somewhere on the page itself maybe the footer

**Comment by adamjonas** [comment]
I'd like to put it right next to the search bar. Maybe with something simple like a + sign.

**Comment by Emmanuel-Develops** [comment]
Alright, I'll draft something up

**Comment by Emmanuel-Develops** [comment]
<img width="1240" alt="Screenshot 2023-02-01 at 11 30 44 AM" src="https://user-images.githubusercontent.com/62019510/216019159-e85d8e66-acd4-47d8-b9d9-048385cad4ad.png">
<img width="1249" alt="Screenshot 2023-02-01 at 11 32 45 AM" src="https://user-images.githubusercontent.com/62019510/216019179-b25325d7-b5e2-4276-82b5-471214f512ef.png">

This is my current implementation. Feedback is welcome

**Comment by adamjonas** [comment]
Modal looks good but let's do something subtle just below the search bar. Some greyed text that reads something like "suggest a source".

**Comment by Emmanuel-Develops** [comment]
Alright. I'll make that in a seperate PR, because we are currently using elastic-search searchbox and it might be an additional weight (to review) if I refactor the searchBox component in this PR.
