### ISSUE TITLE
Pull thumbnails from youtube for transcripts from btctranscript

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/bitcoinsearch-frontend#24]
"The thumbnail url can be determined in the front-end directly... https://i3.ytimg.com/vi/[YOUTUBE_ID]/maxresdefault.jpg"

From @aureleoules

Let's pull those and display them online for the search results that have a YouTube media field.

**Comment by Emmanuel-Develops** [comment]
What if we embed it, so users can go straight to the video from the media

**Comment by adamjonas** [comment]
Let's stick with a link for now.
