### ISSUE TITLE
add sidebar input to be able to find specific authors

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/bitcoinsearch-frontend#7]
<img width="373" alt="Screen Shot 2022-12-16 at 11 15 19 AM" src="https://user-images.githubusercontent.com/755825/208141778-977fb6b1-bc61-4774-a634-532dbda48598.png">

**Comment by Emmanuel-Develops** [comment]
There is an isFilterable prop that enables this. Should the search also apply to domains and tags?

**Comment by Emmanuel-Develops** [comment]
How does this look?
https://user-images.githubusercontent.com/62019510/212469183-44818f5f-3ef6-47c4-948a-53d997334a28.mov

**Comment by Emmanuel-Develops** [comment]
How does this look?

https://user-images.githubusercontent.com/62019510/212469482-d7a217ac-a4c2-4fbe-a884-cb4748019f99.mov

**Comment by adamjonas** [comment]
Looks great! Do keyboard shortcuts (arrows and return key) work for that?

**Comment by Emmanuel-Develops** [comment]
They don't. Tab and spaces do but that is a general behavior for interactive HTML components like buttons, inputs and links.

I can add arrow keys and return functionality for the search. 
Should I write that behavior in this PR? Or create a new issue that addresses that?

**Comment by adamjonas** [comment]
Let's do a pass for keyboard shortcut as a follow-up.
